name: Build Docker images

on:
  # Allow manual runs.
  workflow_dispatch:
    inputs:
      PUSH_IMAGE:
        description: Push image to registry
        type: boolean
        default: true

env:
  PLATFORMS: linux/arm/v7,linux/arm64/v8,linux/amd64
  IMAGE_NAME: cryptpad

jobs:
  build-image:
    name: Build cryptpad Docker image
    strategy:
      matrix:
        IMAGE_TYPE: ["", "-alpine", "-nginx", "-nginx-alpine"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get latest cryptpad version number
        id: cryptpad-version
        run: echo "CRYPTPAD_VERSION=$(npm view cryptpad version | head -1)" >> $GITHUB_OUTPUT

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,v${{ steps.cryptpad-version.outputs.CRYPTPAD_VERSION }}${{ matrix.IMAGE_TYPE }}
            type=raw,latest${{ matrix.IMAGE_TYPE }}

      - name: Build and push ${{ env.IMAGE_NAME }}-${{ matrix.IMAGE_TYPE }} image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile${{ matrix.IMAGE_TYPE }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ inputs.PUSH_IMAGE }}
          labels: ${{ steps.meta.outputs.labels }}
